Part 4 Development Branch
transistasis/PFMCPP_Project4 pull request #4
Opened 2021-08-20 20:02 UTC by transistasis

In this pull request:
* Completed the requirements for Part 4
* Verified that the outputs match
* Confirmed that there are no errors or warnings

2021-08-20 20:21 UTC, matkatmusic requested changes

2021-08-20 20:21 UTC, matkatmusic commented on main.cpp
> +{}
use a `Delegating Constructor`
https://en.cppreference.com/w/cpp/language/constructor
```
Point::Point(const T& a, const T& b) : Point( static_cast<float>(a), static_cast<float>(b) ) { }
```
- [ ] revise

2021-08-20 20:21 UTC, matkatmusic commented on main.cpp
> +    return multiply(float(m));
use `static_cast<>`, not `float()`
`float(m)` is not calling `operator float()` in `FloatType`
- [ ] revise

2021-08-20 20:21 UTC, matkatmusic commented on main.cpp
> +}
pass by const reference.  Are you planning on modifying `m`??
- [ ] revise

2021-08-24 01:26 UTC, transistasis commented on main.cpp
> +{}
Ah, I missed this. Fixed.

2021-08-24 01:39 UTC, transistasis commented on main.cpp
> +}
I made these `const` arguments since they won't be modified.

2021-08-24 05:45 UTC, matkatmusic approved these changes

2021-08-24 05:46 UTC, merged